### ISSUE TITLE
19금방은 에러가 발생하네요

### ISSUE THREAD

**Issue by girlsapink** [hui1601/AfreecaBypassInstallAgent#10]
19금 걸린 방 들어가거나 방송도중에 19금으로 변경하면

일시적인 오류로 방송이 중단되었습니다.
새로고침 버튼을 클릭하여 다시 입장해주시기 바랍니다.

이렇게 나와버리면서 재생이 안되네요.

**Comment by hui1601** [comment]
#9 와 동일한 내용입니다. 자세한 내용은 [여기](https://github.com/hui1601/AfreecaBypassInstallAgent/issues/9#issuecomment-2479296795)를 참고해주세요.
