### ISSUE TITLE
차단되었습니다 실시간으로 모니터링 후 막는거같습니다

### ISSUE THREAD

**Issue by cracker12344** [hui1601/AfreecaBypassInstallAgent#11]

**Comment by cracker12344** [comment]
> 성인또는 비밀번호가 걸려있는 방송이 안봐지는건가요?

아닙니다 실시간 모니터링을 하는데 모니터링후 그리드 1080이 막혔습니다

**Comment by hui1601** [comment]
어제 16시 이후 숲측의 변경사항이 없습니다.
https://raw.githubusercontent.com/hui1601/AfreecaBypassInstallAgent/refs/heads/main/AfreecaBypassInstallAgent.user.js
업데이트 후 재시도해주세요. 다만 아직 크로미움 계열(크롬, Edge 등)에서 성인방송 또는 비밀번호가 걸린 방송은 볼 수 없습니다. Firefox에서는 정상 작동합니다. (#9 를 참고해주세요)

**Comment by cracker12344** [comment]
작동되네요 감사합니다
