### ISSUE TITLE
특정조건에서 오류발생

### ISSUE THREAD

**Issue by TaeDDin** [hui1601/AfreecaBypassInstallAgent#12]
19금+비번방이 같이 걸려 있는 경우 중 특정경우 방송이 "일시적인 오류로 방송이 중단되었습니다.\n새로고침 버튼을 클릭하여 다시 입장해주시기 바랍니다." 라고 나오며 방송이 나오지 않는 경우 발생. (비번방만 걸려있어도 해당경우가 발생할지도 모르겠으나 오류를 발견한 방송은 19금+비번 둘다 걸려있어서 일단 이렇게 표기)
특정경우가 어떤 경우인지는 모르겠으나 대충 테스트 해본결과 
원래 비번방이 걸려있는경우 aid가 400으로 Bad Request가 나오며 다른방법으로 aid 요청을 하는데 
오류가 나오는 방송은 비밀번호 입력창이 떠도 aid가 200 으로 나와 정상적으로 요청이 됐다 생각하고 다른방법으로 aid 요청을 하지않아 발생 하는것 처럼보임

**Comment by hui1601** [comment]
프록시 서버에서 비밀번호 처리에 오류가 있었습니다.
