### ISSUE TITLE
막힘

### ISSUE THREAD

**Issue by girlsapink** [hui1601/AfreecaBypassInstallAgent#4]
숲에서 이제 막았는지 작동이안되네요 개선이 필요할듯합니다

**Comment by hui1601** [comment]
다음 질문에 답해주시면 디버깅에 도움이 됩니다.
1. 언제부터 작동하지 않기 시작했나요?
2. 테스트 환경이 어떻게 되나요? 사용 브라우저, 운영체제
3. 작동이 안된다는 것이 사이트의 디자인이 깨지는 것인가요? 아니면 단순히 설치 안내창이 뜨는 것인가요?

**Comment by mini-kuro** [comment]
11.07 오전부터 사용 안되는거 같네요
파폭 크롬 웨일 다 먹통입니다. 윈도우 11 사용 중이고요

> 3. 작동이 안된다는 것이 사이트의 디자인이 깨지는 것인가요? 아니면 단순히 설치 안내창이 뜨는 것인가요?
화질을 높이려고 하면 고화질 스트리머 설치 안내창이 뜨면서 저화질 상태가 지속됩니다.

**Comment by girlsapink** [comment]
24.11.07 am 10 af에서 업데이트 진행되면서 막힘
크롬 / win 10,11
1080 시청이 불가능함

**Comment by hui1601** [comment]
https://github.com/hui1601/AfreecaBypassInstallAgent/commit/9168e69f5098d228aea67bfca0c0386ecad38d16  으로 고쳐졌습니다.
다음 주소에서 업데이트 해주세요.
https://cdn.jsdelivr.net/gh/hui1601/AfreecaBypassInstallAgent@20241107/AfreecaBypassInstallAgent.user.js
