### ISSUE TITLE
새버전 설치해도 고화질 안되네요

### ISSUE THREAD

**Issue by mini-kuro** [hui1601/AfreecaBypassInstallAgent#5]
241107 새버전 올려주신거 설치하고 들어가봤더니 
여전히 화질 높이려면 고화질 스트리머 설치 안내창이 뜨는 현상이 발생합니다. 
그리드 실행 안시키면 화질은 안올라가지네요.
윈도우11, 웨일 크롬 파이어폭스 모두에서 동일한 버그가 있습니다.

**Comment by mini-kuro** [comment]
![Screenshot 2024-11-07 at 14 25 06](https://github.com/user-attachments/assets/b409b7f9-ad6f-405f-adea-842d5e044a1f)

**Comment by hui1601** [comment]
재설치 이후에도 새로고침 했음에도 발생하고 있는건가요?
메인 페이지에 있는 주소는 캐싱으로 인해 대략 1주 뒤 업데이트됩니다. 다음 주소에서 재설치(Ctrl+Enter)를 해주셔야합니다.
https://cdn.jsdelivr.net/gh/hui1601/AfreecaBypassInstallAgent@20241107/AfreecaBypassInstallAgent.user.js

**Comment by mini-kuro** [comment]
주소 링크 통해서 받았는데 동일하게 스트리머 설치 안내창이 뜨는것 같습니다

**Comment by amata9303** [comment]
엣지기준 새버전 정상작동입니다 감사합니다

**Comment by EOLEUMJAN** [comment]
금일 업데이트 설치 후 정상작동 합니다
윈도우11 엣지
감사합니다

**Comment by hui1601** [comment]
> 주소 링크 통해서 받았는데 동일하게 스트리머 설치 안내창이 뜨는것 같습니다
> @mini-kuro
방금 VM으로 테스트 했으나 여전히 재현할 수 없습니다. 브라우저 캐시 삭제와 고화질 스트리머 삭제 여부를 확인해주세요.

**Comment by mini-kuro** [comment]
Tampermonkey 사용해서 그런가 싶긴 하네요. 기존에는 Tampermonkey로도 잘 작동했었는데 
Violentmonkey 확인해보니 정상 작동하네요. Tampermonkey 문제였던거 같습니다.

**Comment by hui1601** [comment]
스크립트 편집을 활성화 하시고 `unsafeWindow.`를 지우고 저장하면 아래와 같이 만들면 작동하시나요?
```js
Object.defineProperty(LivePlayer.getPlayerInfo(), 'isAbroadCDN', { get: () => true });
```

**Comment by mini-kuro** [comment]
말씀하신대로 unsafewomdpw. 지우고 저장하니 Tampermonkey에서 작동 잘됩니다! 정말 감사합니다!!
