### ISSUE TITLE
업데이트 후 또 다시 막힘힘

### ISSUE THREAD

**Issue by girlsapink** [hui1601/AfreecaBypassInstallAgent#6]
숲에서 업데이트를 진행후부터 이제 작동이 안되네요
![2024-11-13_163024](https://github.com/user-attachments/assets/47fcd959-7816-45c4-97e0-8fd23296ff75)
방에 접속하면 저 화면만나오고 아예 시청을 못하게되었습니다.
수정좀 부탁드려요

**Comment by cracker12344** [comment]
일단 다시 뚫리기 전까지 번거롭지만 해결방법 찾아냈습니다 전

1. 바이올렛 몽키를 끈상태로 시청할 방송진입
2. 저화질로 전환후 540p상태에서 시청중인 방송에서 바이올렛 몽키 다시 켜기
3. 그상태로 방송새로고침후 1080p화질로 전환 후 시청

**Comment by hui1601** [comment]
숲이 해당 스크립트를 차단하기 위해 클라이언트에서 서버로 화질 설정을 전송하도록 패치했습니다.
https://raw.githubusercontent.com/hui1601/AfreecaBypassInstallAgent/refs/heads/main/AfreecaBypassInstallAgent.user.js
여기에서 스크립트를 재설치해주세요.
