### ISSUE TITLE
비번방+19금방에서 오류 발생합니다.

### ISSUE THREAD

**Issue by Dochigi** [hui1601/AfreecaBypassInstallAgent#9]
제 추측상엔 비번방이 오류인 것 같습니다만 해당 방송이 비번+19금이라서 같이 작성합니다.

"일시적인 오류로 방송이 중단되었습니다.
새로고침 버튼을 클릭하여 다시 입장해주시기 바랍니다."만 출력되며 입장이 거부되네요.

그리드 프로그램 안만들어줄거면 우회정도는 이해해주지 ㅠㅠ

**Comment by hui1601** [comment]
코드를 업데이트 했습니다.
https://issues.chromium.org/issues/40450316
크로미움 기준 `User-Agent` 변경을 지원하지 않아 아직 크로미움에서 동작하지 않습니다.
Firefox 는 동작합니다.
비밀번호 기능은 확인해보도록 하겠습니다.

**Comment by Dochigi** [comment]
방금 파이어폭스에서 확인했으나 비번방에서도 파이어폭스는 작동하지 않네요.

**Comment by girlsapink** [comment]
크롬에서는 불가능한건가요? 크롬에서는 아직 19금방 작동을않하는데

**Comment by hui1601** [comment]
https://github.com/hui1601/AfreecaBypassInstallAgent/releases/tag/20241116-3
